### ISSUE TITLE
Theme event fails if it is the first one in a timeline

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1098]
## The problem

If the first event on a timeline is a theme event the style doesn't load properly.

**To Reproduce**
Add a theme event at the start of a timeline
![Screen Shot 2022-08-07 at 01 32 36](https://user-images.githubusercontent.com/2206700/183269026-77f3b3b1-8fb9-4802-a9b9-377236dde8a0.png)

The dialog first event won't display properly.
![image](https://user-images.githubusercontent.com/2206700/183269083-4f2e0211-b1c0-4f55-8beb-7c7f44d7deb0.png)

**Comment by thebardsrc** [comment]
i cant look into it right now myself, but I found a bug earlier where Jump was sometimes making the timeline advance an extra step because of finish(), perhaps something similar is happening here? 

![image](https://user-images.githubusercontent.com/2214793/183276340-edd64b07-f6bc-48d3-a458-88efaff7e327.png)

**Comment by Jowan-Spooner** [comment]
Cannot recreate, setting theme on the first event works for me.

**Comment by coppolaemilio** [comment]
could it be my project then?

**Comment by Jowan-Spooner** [comment]
Assigned to @coppolaemilio so he test this once he has time.

**Comment by Jowan-Spooner** [comment]
Closed. Can be reopened if this is an issue in the future.
