### ISSUE TITLE
GDScript styling update

### ISSUE THREAD

**Issue by willnationsdev** [coppolaemilio/dialogic#11]
Some variations from the official [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html). I would recommend making changes to the codebase to match its specifications, for better cross-maintainability and consistency with the overall Godot community.

With just a quick glance at `editor_view.gd`, I noticed two issues already:

1. Some nodes with PascalCase onready variable names.
2. The spacing of newlines between functions is only 1, not 2.

**Comment by coppolaemilio** [comment]
I'll take a look at the style guide!

1. I use PascalCase for nodes, and since the default way of accessing nodes in godot is so verbose when I create a onready var that it's just a shorthand for a node I follow the same PascalCase as if it was a node.
2. This might be also my preference but I usually have all functions folded and having only 1 spaces makes it really hard to read (I don't have very a good sight 😢

**Comment by willnationsdev** [comment]
@coppolaemilio 

> I use PascalCase for nodes

The "fix" would be to change it to use consistent `snake_case` variable names. Based on the style guide, PascalCase names should only be used for preloaded constants storing `Script` resources (i.e. things that simulate the behavior of classes).

```gdscript
onready var MyNode = $MyNode # bad
onready var my_node = $MyNode # good

const my_class = preload("my_class.gd") # bad
const MyClass = preload("my_class.gd") # good, equivalent to `class_name` keyword
```

> but I usually have all functions folded and having only 1 spaces makes it really hard to read (I don't have very a good sight

From the version of code I was looking at, there was already only 1 space between functions, and there are supposed to be 2.

```gdscript
# good
# function comments for do_something
func do_something():
    pass
# space 1
# space 2
# function comments for do_something_else
func do_something_else():
    pass
```

**Comment by coppolaemilio** [comment]
Sorry! the line breaks I thought that you said "The spacing of newlines between functions is only 1, not 2." as if it was `\n` instead of `\n\n` which is the one I had, I'll update the spacing between functions to be `\n\n\n` now 👍 

For the naming of node references I still kinda prefer to use PascalCase, but will probably also change it so it is more in line with other Godot projects. Thanks!
