### ISSUE TITLE
Better resources UI

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#111]
**Is your feature request related to a problem? Please describe.**
When dealing with a lot of timelines, characters, definitions and themes, it takes a lot of place in the screen and you quickly get lost.

For example, in my project I have 13 timelines, and I am only at the beginning. Splitting my dialog into several timelines makes it easier to organize and maintain (and allows for the autosave to trigger often). However, timelines are sorted by creation date (filename using timestamp), and in a simple list. This can be difficult to find the correct timeline in a long list. 

**Describe the solution you'd like**
In my opinion, the best approach would be to let the user create 'folders' for resources and let him drag-and-drop resources to organize them.

We would also need to edit the pickers in the timeline. It should display a dialog showing the relevant resource's tree (like the `Create New Node` dialog) instead of showing a simple list.

To implement this behavior, a possible solution would be to create folders in the filesystem, and move resource files when the user moves them in the tree. This way the tree structure would be easy to do, and we could sort files by name (instead of filename) to make it easier to find resources.

**Describe alternatives you've considered**
I tried to use naming conventions with specific prefix for resources of a certain type, but as we cannot move them in the list, everything becomes mixed up as your project grows.

**Comment by coppolaemilio** [comment]
The folders was something that was planned initially when I started unifying the item lists, but there is also another feature I want to implement that I never openly spoke about which is the "chapters" view.
The main idea is that each folder (chapter) would host a bunch of timelines and when you select one can see a different view with each chapter as a node in a graph node panel. That way you can better organize your story or branches, and also use new events like "jump to next chapter" etc... 

Moving items would be nice and could probably be accomplished, but haven't tried yet. I suppose you have to add an extra parameter with the place where each item is and load them in that order instead of alphabetically. 

I wasn't planning on implementing any of that for the v1.0 since I believe i18n is more requested and probably will break compatibility, so I'm researching that right now

**Comment by arnaudvergnet** [comment]
I don't think I fully understand how you want to implement chapters, but I guess you'll be able to explain a bit better when you start working on it. Just be careful to keep the plugin compatible for general use, and not specific to visual novels.

I'll work on a PR to at least sort resources by name so we can organize them using a prefix system. I'm working a game (visual novel) with a lot of choices, I'll report back to you to see if it is easy to use.

Sorting using a tree seems like a lot of work as we would have to remake pickers, so I'll leave the idea for now.

**Comment by coppolaemilio** [comment]
> Just be careful to keep the plugin compatible for general use, and not specific to visual novels.
I'm a bit concern about this thing actually. I'm also creating this for a visual novel I want to make, but I found that a lot of people want to use it for any kind of dialog. I'm not sure it is possible to make something of a broad general use without making it too complex. I think there are a lot of other dialog plugins for godot (and many more will be made) that could acomodate people better if they need something more flexible. I don't want to turn any ideas or anyone away, but some times when I start to think in to all the scenarios where dialogs can happen it can be a bit overwhelming to believe that Dialogic will be good at all those. So I might prefer for this to be more of an rpg/visual novel editor rather than a one size fits all (but poorly). 

I'll share some mockups for the chapter feature whenever I have the time to make them 😅

**Comment by arnaudvergnet** [comment]
> I'm not sure it is possible to make something of a broad general use without making it too complex.

You are right, this could become way too difficult to manage. But right now it can be used for basic dialogs for many types of games (just remove the background and show your game behind), it would be a shame to lose that.

You could state in the readme that it is made for visual novel, this way you will avoid unwanted feature requests.
