### ISSUE TITLE
Portraits are added twice

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1121]
@thebardsrc When using the Join event the portraits are added twice, not sure why. 
Also they are not added to the PortraitHolder anymore, but to the positions themselves. Maybe that's intended, not sure.

**Comment by thebardsrc** [comment]
> When using the Join event the portraits are added twice, not sure why.

Hm I didn't see that myself in testing, but i'll check it out

> Also they are not added to the PortraitHolder anymore, but to the positions themselves. Maybe that's intended, not sure.

Custom portrait scenes were being added to the position themselves, I copied  how that that method with the new PlainPortrait scene.

**Comment by thebardsrc** [comment]
ohhh ok. so I dug through more, because you really had me confused with that PortraitHolder statement because I didn't remember touching anything about that... It got removed from the code entirely during one of the initial Godot 4 conversion changes

which, honestly, is most of the change i wanted to make to begin with, I _want_ them in a node like PortraitHolder for the character sorting and other things. so, perfect, it's already there, I just have to put them back on it
