### ISSUE TITLE
add `equal to` to Set variable event.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1151]
Right now, when you click the input field, it opens the list of existing variables. This makes it seem like you can't input a new value to the field. 

![image](https://user-images.githubusercontent.com/2206700/186416764-a3516dc8-4408-4130-90f7-14c2188bdd74.png)

When the dropdown is set to `to be` it should not suggest any variable. We can add a new option `equal to` that will show the existing variables for you to select.

**Comment by Jowan-Spooner** [comment]
The problem with this is that the event is stored as `VAR {test} = Something` or `VAR {test} = {Counter}` and there is no differentiation if the value is a string or a variable in the text format.

Also I find `equal to` strange because it sounds like a boolean operation instead of an assignment. 
I would rather have
- to be
- to the value of

Just my opinion tho

**Comment by coppolaemilio** [comment]
> The problem with this is that the event is stored as VAR {test} = Something or VAR {test} = {Counter} and there is no differentiation if the value is a string or a variable in the text format.

For the visual editor we can check if `{}` exists to show one or the other. 

For the label in the drop-down, maybe like:
`To be the same as`

**Comment by Jowan-Spooner** [comment]
Will move to 2.x milestone because while it would be nice, this is not something we need for beta or inital release.

**Comment by Jowan-Spooner** [comment]
Not relevant anymore since you can select the type of the value now.
