### ISSUE TITLE
Support for generic write-in characters directly in the text event

### ISSUE THREAD

**Issue by thebardsrc** [coppolaemilio/dialogic#1170]
From Discord: "Request support for just generic write-in characters directly in the text event.
For when a character only have a temporary role, and don't need a character file. It gets messy when a character who only appears with two lines in one scene needs to be defined as a character."

should be real simple to implement, with simply surrounding it in special character that can't be part of a filename. Something like this:

`*Temporary*: Hi, I'm just a guest here`

Mostly just depends on which special character works best with the regex without rewriting it (if possible)

**Comment by coppolaemilio** [comment]
Do we need to specify it is temporary? what if we make it show on the name label as if it existed when it doesn't find the character associated to it? That way it would just be
`Temporary: Hi, I'm just a guest here`

**Comment by thebardsrc** [comment]
for performance reasons its better to have an actual designiator IMO, so it knows ahead of time not to bother searching for the character because it's not going to exist

**Comment by Jowan-Spooner** [comment]
I wonder if people would want to also specify a color for a temporary character... And how that could look in the text format.

**Comment by coppolaemilio** [comment]
I would not go into more hypotheticals there, I think just a name should be fine 😅  if some of you want the feature for a game you are working on it can be implemented, otherwise it will have some technical debt associated with that that we shouldn't risk at the moment. 

Recognizing non-character names even if it comes at a performance cost I think is worth it as a "fallback". But I would love to see how slow it is before trying to optimize for lookup speed.
