### ISSUE TITLE
Adding events per drag and drop doesn't work

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#1183]
Probably something blocking the mouse.

**Comment by coppolaemilio** [comment]
I'm trying to understand an error when drag and dropping an event to the timeline editor. It currently fails because this line checking for the event_script.can_contain_events fails because: res://addons/dialogic/Editor/VisualEditor/VisualEditor.gd:756 - Invalid get index 'can_contain_events' (on base: 'GDScript'). I'm not sure if you want to give it a go and see what alternative check can happen there 🤔  I don't really understand how to fix it at the moment

![image](https://user-images.githubusercontent.com/2206700/195987988-fb66a86d-6de2-4e2b-87a7-f7510d262231.png)

**Comment by coppolaemilio** [comment]
A video of the action needed to trigger the error:

https://user-images.githubusercontent.com/2206700/195988147-e46866d4-b4e9-4f0d-9bdd-a4cc77a133d6.mp4
