### ISSUE TITLE
Setting Variable Value via Dialogic Singleton has No Effect

### ISSUE THREAD

**Issue by ellogwen** [coppolaemilio/dialogic#125]
Maybe I misunderstood how the definitions/variables work, but I am trying to change the value of some defined variables before I start the dialog, to access the values inside the timeline. However, the definitions do not change from their default value.

```
	Dialogic.set_variable("random_roll_D2", (randi() % 2) + 1)
	Dialogic.set_variable("random_roll_D6", (randi() % 6) + 1)
	Dialogic.set_variable("random_roll_D20", (randi() % 20) + 1)
	dialog = Dialogic.start(timeline_name, false)
	dialog.connect("dialogic_signal", self, "on_dialogic_signal")
	add_child(dialog)
	prints(Dialogic.get_definitions())
```

What did I do wrong?

Here is a screenshot of the timeline in question
![image](https://user-images.githubusercontent.com/22261975/112876614-01059700-90c6-11eb-894b-53357f7ca769.png)

**Comment by ellogwen** [comment]
ok, I kind of figured it out. Since the definitions get emptied and defined in the _ready function, I have to set the variables after I added the dialog to the scene tree, which is a bit awkward, because it immedietly starts and you may not have access to the correct values at the start of the timeline. For this kind of timeline, where the If branch comes not as the first event, it works that way

**Comment by arnaudvergnet** [comment]
As you found out, saves are read from the json file when the dialog node is added to the tree, this is the issue.

When using `set_var` and `set_glossary`, the values are kept in memory in the singleton, but not written to the file. The actual saving to file happens only on timeline end/start to prevent loops (eg: you do +1 in the timeline, the user exits the game, starts again, and gets an other +1, so it ends the timeline with +2 instead of +1).

This system is quite recent and definitely has room for improvements.

A way to fix this would be, as you say, to decouple definitions and the dialog node. Maybe loading data once when the singleton is created, not when the dialog node is created.

A simple workaround is to force saving definitions before loading the dialog, by calling `save_definitions()`. This should write the current definitions to the json. Make sure you called `DialogicSingleton.init()` before calling this function, otherwise the current save wont be loaded and you will overwrite the data.

**Comment by arnaudvergnet** [comment]
I pushed a PR to fix this issue. Maybe you can try it and tell me if this fixes your problem?

I edited one line, to reload definitions from the json file only if the user wants to reset saves. Because saves were already loaded on singleton init, it wasn't necessary to reload them each time the node was added to the tree.

**Comment by ellogwen** [comment]
Thank you, this seems to work for my instance. Don't have checked any sideeffects tho, skipping the init. Time will tell :)
