### ISSUE TITLE
Changing dialogue box's size

### ISSUE THREAD

**Issue by kittygyj** [coppolaemilio/dialogic#1456]
I noticed that the dialogue box is very small comparing to my game screen. I think it would be great to have a feature of dialogue box's size customization.

**Comment by Jowan-Spooner** [comment]
Hi, I think this a fine addition to make. 
However in 2.0 we are trying to keep the customization options to a minimum. You can of course edit everything by creating a custom copy that you just edit in the godot editor. So the customizer won't have as many special settings as in 1.x. This seems like a good addition though because the default layout should at least work on all kinds of games.
