### ISSUE TITLE
Support the Godot 4 translation system / merge the translation system

### ISSUE THREAD

**Issue by Bricklou** [coppolaemilio/dialogic#1493]
**Is your feature request related to a problem? Please describe.**
For now, Godot and Dialogic translation systems are separated. This is still usable, but not practical when we need to export them to tools like Weblate.

**Describe the solution you'd like**
It would be interesting if Dialogic dialogs were completely supported by the Godot translation export with the ability to put some context (like: `msgctx: dialog character: A....` in PO files), this way all the translations and dialogs are centralized in one single file and importable in external tools.

**Comment by Jowan-Spooner** [comment]
Hey. Supporting translations with .pot/.po files is of course not entirely impossible. I would like to clarify the reasons why we've decided against it so far:

***It's also a built-in way to translate in godot***
first of all .csv translations are also a built in godot translation system. It's simply that godot has two ways of using translations, either with csv or with gettext.

***.csv files are easier for beginners to understand***
As even the godot docs state, using .csv files is simpler and only requires programs most users already have. It's a simpler process, which is great, as dialogic is also used a lot by hobby-developers and less by big studios/professionals.

***.po files don't work with ids***
Gettext translations usually use the english text as the identifier. The dialogic translation system is setup so that you can edit timelines even after creating the inital translation csv, because events are assigned unique ids that are used instead of the actual texts. This is great, as unlike for big studios, the workflow with dialogic often isn't: First finish the game, proof-read everything, then translate; these steps are more mixed up.

***Context and pluralization less important***
The main advantages of gettext translations are context and plural. These are not as important though for dialogs in which most translatable text is complete sentences, not single words like in UI's. Also because the keys are usually something like `Choice/a1/text` at least some context is given to what each string is meant to do. 


***It's just more work that's hard to do for us***
Lastly, also keep in mind implementing the dialogic translation system with csv was just a lot easier as we have noone on the team really familiar with .po files.

This does in no way mean gettext translations will never come to dialogic. It's just why I've not considered it important so far.
I can see that supporting industry translations tools would certainly be useful for those familiar with them. Maybe it will come in the future.

**Comment by Jowan-Spooner** [comment]
I'm closing this in favor of the more informative/direct request issue #1874
