### ISSUE TITLE
Background event allows you to select scene but it doesn't work

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1522]
![image](https://user-images.githubusercontent.com/2206700/233811692-d7f8bef8-0299-4dd8-94b5-be888fecf42c.png)
The background event file picker let's you select a scene but it doesn't work when you do it this way. You have to use the advanced options for it to work. It feels very disjointed since when you select the scene the event changes the header input to the "argument" one. 

![image](https://user-images.githubusercontent.com/2206700/233811749-d652decf-c9e4-442c-a011-50d9e4c6c339.png)

**Comment by Jowan-Spooner** [comment]
The only real bug here is that the File picker allows to select a scene. Behind the scenes the image picker and the argument field are the same thing: They allow specifying a string argument for the background scene. It's just that the default background expects this argument to be a file name so by default the field is a File picker.

I didn't want to put the scene picker into the header as most people will use the default scene with images and I really want the header to only contain really important stuff. 

One idea for a better UI/UX could be to add a "advanced toggle" that reveals the scene picker and argument field.
Also fade time should be capitalized.

**Comment by Jowan-Spooner** [comment]
Update: 
You can now not select a scene in the image picker anymore. This doesn't solve the issue of the scene picker being quite hidden.
