### ISSUE TITLE
There should be a setting to select the default audio bus for each type of event

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1528]
![image](https://user-images.githubusercontent.com/2206700/233843968-6be2314c-012b-450d-a61b-dd67f6f8608f.png)

Right now, you have to manually select the audio bus, but I think there should be an "Audio" page on the settings with the default busses for each type of event, so that when you create them they are the same as in your settings.

That way, if you want to modify one audio bus later you can change it manually.

**Comment by Jowan-Spooner** [comment]
I have actually been thinking if we should add a way to change the default value of ANY event setting, because I'm sure some people would want to have characters join at position 234 by default (Character Event), have a default wait time of 3.414 seconds (Wait event) and an alternative choice text of "You cannot choose this you idiot" (Choice event)...

As arguments can be much more easily gathered now anyways (like for the autocompletion of the text editor) something like this would certainly be possible, but it might be easier to add settings for the important ones.

Let me know what you think.

**Comment by coppolaemilio** [comment]
That sounds like a great idea. Having a settings tab with default that lets you overwrite any of the default input fields from any event would be an amazing thing to have. If it is too much we can start slowly adding the ones we already identified.

**Comment by Jowan-Spooner** [comment]
I will take a look at it. I might combine it with a couple of other module-related stuff I wanted to built, like a way to disable some modules, even when they are installed so people can clear up the event button sidebar to contain only what they really need.
