### ISSUE TITLE
Variables don't update

### ISSUE THREAD

**Issue by SkaOArt** [coppolaemilio/dialogic#1544]
I don't know if this is a bug or not. 
But it's really ennoying to update every condition if you change a name of an varible.
If you use one varible in 4 placed you have to update them four times. 
So you can't really edit them, when you don't want to do them.

Describe the bug
If you rename an varible the condition will point to the older varible name. 

Expected behavior
variables will update in all timelines when they've been edited.

**Comment by Jowan-Spooner** [comment]
This has been talked about on discord, I just want to add what can be said already. as this is an issue that should be fixed, but it isn't an easy one. 

Many things are now saved as strings instead of id's in timelines. This includes: Variables, Characters, Portraits & Animations. This means if any of these is used in a timeline and then renamed afterwards, the connection breaks. 

This is hard to work around but super annoying for users as well.

The best solution would probably be to add some `replace in timeline files` tool that will be triggered automatically sometimes. 
It's hard for me to tell how taxing "searching ALL existing timelines whenever a variable is renamed" turns out to be. But I think something similar is done by godot's file system whenever you move or rename a file.
