### ISSUE TITLE
Selecting a selected event should unselect it.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#155]
**Is your feature request related to a problem? Please describe.**
The problem is my brain trying to unselect the event all the time 😭 

**Describe the solution you'd like**
When you selected an event, there is no way to unselect it. So either clicking outside of the timeline or clicking again on it should unselect it.

**Describe alternatives you've considered**
I tried getting rid of my obsession but I couldn't

**Additional context**
Send help.

**Comment by arnaudvergnet** [comment]
I tried doing that, but failed miserably. The problem is with the drag event. If you unselect on click, when dragging a selected event it will unselect it, which is not intuitive. I tried unselecting when clicking outside of the timeline, but didn't understand godot's gui and my click never got registered.

**Comment by ellogwen** [comment]
Maybe i can take a look

**Comment by ellogwen** [comment]
Ok, I got it to work to select/deslect but still proper drag, however, unselecting while clicking somewhere outside did not work with the current control structure. maybe I can take a look at it this evening

**Comment by ellogwen** [comment]
>I tried unselecting when clicking outside of the timeline, but didn't understand godot's gui and my click never got registered.
This could be due to that the gui_inputs are connected on the pieces and not the timeline itself
