### ISSUE TITLE
Option to specify who a character is talking to

### ISSUE THREAD

**Issue by nlupugla** [coppolaemilio/dialogic#1550]
I read #1413 suggesting a two character RPG mode and it inspired me to think of a slightly more flexible approach in which a Text event allows you to optionally select who a character is talking to in addition to selecting which character is doing the talking. 

I am currently working on a game where much of the dialogue consists of one character on the left side of the screen (usually someone in the player's party) talking with another character, mirrored, on the right side of the screen (usually an NPC). I can get the job done with a lot of Character Join and Character Leave events, but it's error prone (I might forget a Character Join or Character Leave event) and when I read over my timeline, it's not immediately clear who is talking to whom.

What would people think about giving the user the option to specify who a character is talking to? If the user specifies a listener, all characters other than the speaker and the listener leave, then the speaker and listener would join if they aren't already in the conversation. The listener would always be mirrored relative to the speaker.

Here's a quick example I came up with. First is a conversation written out in the current Dialogic syntax.

``` GDScript
Join Alice 1
Join Bob 2
Alice: Bob, will you go to prom with me?
Bob: Nah, I have other plans.
Leave Bob
Join Charlie 2
Charlie: I'll go with you Alice!
```

Here is the same conversation written out using the proposed optional listener system.

``` GDScript
Alice -> Bob: Bob, will you go to prom with me?
Bob -> Alice: Nah, I have other plans.
Charlie -> Alice: I'll go with you Alice!
```

As you can see, the timeline is shorter, and easier to parse at a glance. Obviously, the "->" syntax is just a placeholder and can be changed to something better if people prefer. I think with smart default values, this system would essentially allow for the two character RPG mode mentioned in #1413. If there was interest, one could also allow for multiple speakers and multiple listeners.

What do people think?

**Comment by coppolaemilio** [comment]
Hello thanks for the proposal!
I'm not sure I'm convinced about this setup in particular. I think you should probably make custom events with different colors that suit your needs, one for the left slot and one for the right slot. That way, you can easily add or remove characters from one side or the other. This particular setup you are describing doesn't seem to fit with the generic goal that Dialogic has, but since Dialogic 2 is quite extensible, you should be able to make the specific changes you need for your game. For future proposals I encourage you to use  the discussions page: https://github.com/coppolaemilio/dialogic/discussions

Thanks again!
