### ISSUE TITLE
Pauses and Auto-pauses are not affected by [speed=x] text feature, add a global speed that does.

### ISSUE THREAD

**Issue by phantomdesvin** [coppolaemilio/dialogic#1614]
**Is your feature request related to a problem? Please describe.**
When I use the [speed=x] text feature, I only get the letter by letter display speed modified, but the auto-pauses remain the same, so the speed is not changed uniformly and the result is not that great.

**Describe the solution you'd like**
Adding a global speed [gspeed=x] to the text features would be great to have the speed of the text actually changed entirely, not only the speed of the letter by letter displaying, but also the autopauses and pauses that are not affected by the current speed feature.

**Describe alternatives you've considered**
Maybe the global speed should be called just speed, and the current letter by letter speed should be called other way. I don't care too much about that as long as we have a comfortable global speed we can use in text.

**Comment by Jowan-Spooner** [comment]
Something similar was discussed before, so I could see this happening before the 2.0 release. 
Text speed is a very essential feature of dialog display so it's a priority imo.

As far as I can see it these are the things we need:

- **text-speed** (a speed multiplier)
   - defaults to 1 (so has no effect by default)
   - can be modified mid-text with [speed=x]
   - affects letter-speed, autopause speed and pause_speed

- **letter-speed** (previously text speed)
   - can be set in the DialogText settings 
   - can be modified mid-text with [lspeed=x] (or something similar)

- [lspeed=x] and [pause=x] should be able to specify an absolute speed
   - for example [pause=$x] or [pause=!x] idk. 
   - In this case the speed would NOT be multiplied with the text-speed

- user_speed setting (another speed multiplier)
    - Lastly another speed multiplier would be useful to implement a text-speed setting in games. I think this multiplier would affect any speed that is also affected by the built-in speed-multiplier.


This would mean:
- if you just want to have the behaviour we had before you would use [lspeed] instead of [speed]
- if you want what you described above, you would use [speed] which uses a very different scale now, but affects auto-pauses and [pauses] as well.
- you can also mix these workflows
- you can ALSO implement a text speed setting for players. This speed setting would again multiply letter speed and autopauses and pauses.

**Comment by phantomdesvin** [comment]
That would be perfect. But if the word by word feature is implemented maybe we should think about a speed name less specific than letter speed to make it work with word by word display speed too. Maybe dspeed is a good option, as default speed (the name displayed on the Dialogic editor settings right now) or display speed, and I think tspeed as typing speed or text speed could work well too.

**Comment by Jowan-Spooner** [comment]
I'll try to implement this now.

**Comment by Jowan-Spooner** [comment]
This has been implemented by #1718. 

[speed] is now a multiplier that both affects [lspeed] (new, like previous speed) and [pause] unless those provide their value with =x!.
