### ISSUE TITLE
Error using dialogic_signal

### ISSUE THREAD

**Issue by DefoeDoes** [coppolaemilio/dialogic#1757]
When I'm trying to use connect() to listen to signals from the timeline, I get this error: 

`Error at (17, 39): Invalid argument for "connect()" function: argument 2 should be "Callable" but is "res://Scripts/Intro.gd".`

This is my code: 
```
extends Node2D

func _ready():
	pass # Replace with function body.

func _process(delta):
	pass


func start():
	var dialog = Dialogic.start('Intro')
	add_child(dialog)
	dialog.connect("dialogic_signal", self, "dialog_listener")
	$AnimationPlayer.pause()

func dialog_listener(string):
	if string == 'resume':
		$AnimationPlayer.play()

func pause():
	$AnimationPlayer.pause()
```

System OS: Windows
Godot version 4.1.1
Dialogic version 2.0 alpha 9

*Edit: formatting*

**Comment by Jowan-Spooner** [comment]
This is due to the connect method being different then in 3.x. You now connect to a callable (the method name as a reference (not a string and without brackets):
`Dialogic.connect("dialogic_signal", dialog_listener)`

However in 2.x is there is NO signal called dialogic signal. Read all about the signals that exist now and how to connect them here: https://github.com/coppolaemilio/dialogic/wiki/Tutorial:-Dialogic-Signals

Also note that in 2.x you should NOT add the layout manually and that the signals are not on the returned layout but on the Dialogic singleton. The corrected start method would look like this:
```
func start():
     Dialogic.start('Intro')
     Dialogic.signal_event.connect(dialog_listener)
     $AnimationPlayer.pause()
```
Hope this helps.
