### ISSUE TITLE
Portrait Mirror only works when character joins and affects following portraits

### ISSUE THREAD

**Issue by NinoM4ster** [coppolaemilio/dialogic#1904]
## The problem

**Describe the bug**
When a character joins a timeline, the Mirror setting of the portrait it's set to decides the direction of it and all the following portraits, even if they are not flipped in the settings. Setting a portrait on Text nodes after that has no effect on the portrait direction and completely ignores it's Mirror setting.

**To Reproduce**
1. Create a character with two portraits ("one" and "two" for example)
2. Enable the Mirror option of portrait "two"
3. Create a timeline
4. Add a Character Join node with the created character and portrait "one"
5. Add a Wait node
6. Add a Text node with the created character and portrait "two"
7. Play the timeline, observing portrait directions
8. Invert the Mirror settings (enable on "one", disable on "two")
9. Play the timeline again

**Expected behavior**
On the first run, portrait "one" should not be flipped, portrait "two" **should** (but isn't).
On the second run, portrait "one" should be flipped, portrait "two" **should not** (but is).

**System:**
 - OS: Windows 10
 - Godot Version: 4.1.3.stable.official [f06b6836a]
 - Dialogic Version: 2.0-alpha-11

## Solutions

**Workaround**

Making a character leave and join again does seem to set the correct direction, but there's no way to set "None" as the animation.
Using a Character node set to Update **does not fix it's direction**.
The only option is to flip the actual image file using an image editing software.

**Comment by Jowan-Spooner** [comment]
Heyhey @NinoM4ster, thanks for your issue. 

Dialogics portrait mirror system is pretty hard to understand so here is how it's SUPPOSED to work. While there might be bugs in it rn, it sounds as if your problem is that you are expecting it to work differently. I'll try to clear the confusion. Also I'm still open to discussion on IF this is the best way to handle mirroring.

## Current Intentions
There are 4 different places where you can affect portrait mirror:
- the portraits settings
- the character settings
- the character event settings (JOIN, UPDATE)
- the portrait holder (not relevant for the default layout)
*Importantly, these ADD up, not REPLACE each other.*


**The idea is the following:**
- The portrait mirror setting is intended to allow adjusting portraits that are (for whatever reason) differently aligned then the other portraits of that character. Usually you'd want all portraits facing the same direction by default.
- The character mirror setting is intended to allow adjusting a character that is differently aligned then the other characters.  Usually you'd want all characters facing the same direction by default.
*Setting up your character and portraits all facing the same way, makes it easier to use them correctly in timelines.*

- The direction in game should always be controlled with the character event settings. So when joining you can tell dialogic which direction a character should face. This is not "per-portrait" but for the character so changing the portrait will keep this intact. This way you can specifiy a character that joined on the left to face to the right or vice versa. 

- If you want to change the direction a character faces you have to use a Character Update event and set the desired mirror there. 

- *Lastly each portrait container also has an additional mirror setting. This can allow you to automatically mirror characters in certain positions (e.g. to always make them face the center by default). This can be useful, but can also be confusing to handle (as mirrored and not mirrored on the character event suddenly mean different directions depending on the position) so it's not enabled by default.*

If dialogic does not follow the above rules, then it's indeed a bug. However what you described sounded more like a different idea. Feel free to disagree with this approach and describe your use-case for other solutions.

Hope this helps.

**Comment by NinoM4ster** [comment]
Hello Jowan! Thanks for the quick response!

The first use-case you mentioned was indeed what I was trying to achieve (flipping a few individual images where the character was facing the wrong way), but there was a bug which prevented that from working correctly. It was late when I wrote this so maybe I could have worded the issue more clearly, my apologies.

The PR #1905 actually fixed this issue so I'll close this now, thank you very much!

**Comment by Jowan-Spooner** [comment]
I'm glad it fixed the issue for you. Portrait mirror was indeed not correctly updated when switching portraits. Thanks again for the issue. 
Always question things! ;)
