### ISSUE TITLE
Background Event errors when trying to load a scene as a background

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#1946]
## The problem

**Describe the bug**
When you set a Background event to use a scene as a background, it fails to do so.
First issue here:
![image](https://github.com/coppolaemilio/dialogic/assets/2206700/13cc1b87-7dbf-41f7-8f56-abe123279675)

Second:
![image](https://github.com/coppolaemilio/dialogic/assets/2206700/7058f222-1b4b-46a7-9b03-dc7831afd200)

If I comment out those two lines, then I get these:
![image](https://github.com/coppolaemilio/dialogic/assets/2206700/a27e4112-6c45-4934-b83b-109fa765c6fa)

and when I comment out all both
```
#new_node.get_meta('node')._update_background(argument, fade_time)
#new_node.get_meta('node')._custom_fade_in(fade_time)
```
it finally works and it runs the timeline with the custom background as expected.

**System (please complete the following information):**
 - Godot Version: 4.2.stable
 - Dialogic Version: (latest, main)

## Solutions
Commenting out these lines work, so I guess something might have changed since the last time this was implemented.

**Comment by Pheubel** [comment]
I think that the reason why this problem pops up is because the scene you tried to use did not have a script extending the `DialogicBackground` class.

There is actually a check in place if the script on the root of the scene is (extending) `DialogicBackground`, but this check happens _after_ the damage has been done.

There are really 2 ways for this problem to be solved:
* put the check in the `add_background_node` function and enforce the developer to extend from `DialogicBackground`
* make the code in the subsystem check for the existence of functions instead of relying on typing to dictate functionality.

The assignment of a viewport is not strictly required inside of the background subsystem, as it gets fetched from the newly fabricated node anyways, but it could be used inside of the background scene itself for advanced use. a bit of an edge case. If going with the second way of solving this problem, one way to go about the viewport property is to check if it exists before assigning it, if we want to keep it.
