### ISSUE TITLE
Character Join Main Event deletion when clicking off current timeline

### ISSUE THREAD

**Issue by zakary93** [coppolaemilio/dialogic#216]
I downloaded the WIP 1.1 today from main branch and **if you click off a Timeline to do anything else, all Character Join events are deleted from that Timeline**. It happens every time, not just sometimes. I checked all the other Main Events and none of them seem to have this issue for me personally so far. I tried closing the project and reopening it to see if they might have popped back up (sometimes bugs like this get fixed that way and is useful to know) and it does not. I am on Windows 10 w/ 6th Gen Intel I7 and GTX 1070 on laptop (prolly doesn't make a difference but who knows). Anyone else have this problem yet?

**Comment by coppolaemilio** [comment]
I'm trying very hard but I can't reproduce. Did you remove the previous `/addons/dialogic` folder before updating?

**Comment by zakary93** [comment]
This is in a fresh project. I just made another fresh project just in case I accidentally messed up somewhere to test against and same result. Also, this is Godot 3.2.3? I will check how it works in 3.3 RC8 to see if the issue persists there as well.

**Comment by zakary93** [comment]
Just checked WIP 1.1 in 3.3 RC8. Also, does not work for me there either.

**Comment by Jowan-Spooner** [comment]
Yes. I introduced this with the introduction of the mirror setting. I'm very sorry. I didn't know the timeline looks for a set of very specific settings to find out what event it was. Because of this it wouldn't know it's a join event (and not add it). I'm so happy if the event_id is finally added! Puh. The fix is just one line of code. I am making a PR instantly.
