### ISSUE TITLE
Set a different theme for each character

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#231]
**Is your feature request related to a problem? Please describe.**
It could be interesting to have a different theme for each character (for example Undertale) to give them more life.

**Describe the solution you'd like**
For each portrait/Expression, allow choosing a theme like we can choose a protrait.

**Describe alternatives you've considered**
Right now we must change the theme each time the character starts talking, which is really time consuming a prone to errors.

**Comment by Jowan-Spooner** [comment]
I want to get back to this, as this feature was requested by EmmaH. 

### What?
Basically you add a theme selector to the character editor and whenever that character says something this theme is loaded, and afterwards the default theme is loaded back. 

### Why?
Now while I don't fully know what EmmaH wanted to use this for, I think this would be a cleaner solution to #457 and #364 then adding these settings individually. Why? Because
A) the character editor's UI is pretty messy already as described in #497. Adding more settings wouldn't help with that?
B) There will surely be some other theming feature that someone would like to set per character, next week. So over time we would just replicate all the theme settings in the character editor.

### The problem
While not totally necessary for this to work, Theme inheritance (#232) would drastically improve the usability of this feature. If it doesn't exist having many very similar themes will get annoying very soon when you want to change one thing for ALL characters.

**Comment by timkrief** [comment]
Theme inheritance would definitely be necessary for this to make sense, but it would be an elegant solution to multiple issues.
