### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Sevord** [coppolaemilio/dialogic#249]
*This plugin does not seem to support languages other than English
Maybe it's a coding problem?*
But that is very important multi-language support for various game developers
in fact，i use english code and i am chinese 
but it is  impossible make a English conversation game

**Comment by coppolaemilio** [comment]
Multi-language support will come eventually to Dialogic. Right now we have other priorities but we will get to it :)

**Comment by arnaudvergnet** [comment]
Related to #20, #21, #182

**Comment by Sevord** [comment]
OK. 
Experienced plug-in.
Waiting ： ）

**Comment by Jowan-Spooner** [comment]
Small update: There is a begining of hope with #470 (working translation in the version 1.3)

**Comment by Jowan-Spooner** [comment]
The dialogic UI has been translated partially into spanish, french, german and chinese. Far from perfect, but I think it's far enough that now it's more a question of improving then implementing.
I will close this because in game translation has it's own issue #343. For further requests regarding specific translations or such, feel free to create a new issue
