### ISSUE TITLE
Dialog fade in / fade out animations

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#25]
Not sure how I will set up this one, but if I had to add one a simple opacity fade could work.

**Comment by Crystalwarrior** [comment]
I suggest to make it completely user customizable, for example Ace Attorney pops in dialogue by sliding it up from the bottom instead of fading it out/in. Plus it's context sensitive, so it instantly hides the text box when your character objects, slides towards your character, hangs on the frame and slides the textbox in from the bottom of the screen.

Video example:
https://youtu.be/7okb1lPD9MY?t=899

**Comment by coppolaemilio** [comment]
Yes, it would probably be better to give many options, but I don't think I can work on this one at the moment since there are a lot of things in my list. Maybe the best solution would be to support any user-made animation using the animation player so you can set it up as you want. Thanks for the video reference!

**Comment by mak448a** [comment]
How would I go about doing this? I have a vn box for my game that has the VN box pop up whenever the player talks to someone. I would like it to fade out just like it fades in. Could you please explain how this works?
