### ISSUE TITLE
Add sound effect options in theme settings

### ISSUE THREAD

**Issue by BestestHD** [coppolaemilio/dialogic#260]
i sort of did it manually for text advancement but i think it breaks something lol

But, basically a function that plays sound effects when advancing text, selecting a dialogue choice, etc.

**Comment by coppolaemilio** [comment]
@timkrief were you going to add this to Dialogic? Otherwise I can try to implement it myself

**Comment by timkrief** [comment]
Yes I am working on it.

**Comment by timkrief** [comment]
There's a PR now :) https://github.com/coppolaemilio/dialogic/pull/342

**Comment by timkrief** [comment]
https://user-images.githubusercontent.com/14089949/120888749-5c8a5e80-c5fa-11eb-99c8-46ed8a400e88.mp4

**Comment by BestestHD** [comment]
>  rec-2021-06-05_12.32.37.mp4

Sorry for dwelling on this, but could there be an option to make the sound play only once as well, rather than repeating?

**Comment by timkrief** [comment]
Okay that would be an other type of sound effect that is going to be added later.

**Comment by Jowan-Spooner** [comment]
@timkrief Do you think you still wanna do this? And if so then what do you think when you will find time for it?

**Comment by timkrief** [comment]
@Jowan-Spooner Yes I started doing it, but every time I want to tackle it I feel intimidated in introducing the necessary data structures. I'm making a sub-scene for audio track settings. Each audio effect will be using this scene in the settings, but then I can't use singular setting for each of the sub-setting or it would be messy. I tried to imitate how it was done for the button layouts settings and I think I should do something similar but I still feel like I'm going a bit out of what's already have been established. The feature is not far from being implemented, it's just that I don't want to do it "the wrong way" and since it's not my code base, I don't really know what would be considered "the wrong way". Maybe I can make something on a fork and show it to you all so that we can check if I can continue with it.
