### ISSUE TITLE
Allow functions that return true/false to be used as conditions for if blocks.

### ISSUE THREAD

**Issue by Sslaxx** [coppolaemilio/dialogic#263]
**Is your feature request related to a problem? Please describe.**
Related to a comment Emilio replied to on https://www.youtube.com/watch?v=sYjgDIgD7AY&lc=UgxfBRamwDlNwM4N05Z4AaABAg.9Mb15MKypDc9MbHkER6-oS

**Describe the solution you'd like**
Allowing an `if` block to be able to take a function that returns a bool value to be used as a condition.

**Describe alternatives you've considered**
You could just use definitions of course, but a function returning a value could give more access to Godot's functionality.

**Comment by bitbrain** [comment]
@Sslaxx where exactly are you envisioning where this function code lives? Also, what kind of logic would you use in that function that cannot be done within the editor at the moment?

**Comment by coppolaemilio** [comment]
Closing as I don't fully understand it. Feel free to re-open if needed.

**Comment by jonbonazza** [comment]
@coppolaemilio I'm running into this as well. For instance, I have a "Blackboard" auto load that allows me to just set and get arbitrary flags as data. I want to check for a certain flag here in a timeline Condition. However because it doesn't use Dialogic Variables, I can't use a Variable condition, and because the Condition's Expression doesn't load in autoloads, it can be used in expressions to evaluate for the Condition. 

I think a simple solution here would be to pass in all autoloads when executing the Expression, so that the they can be used in the Expression syntax.
