### ISSUE TITLE
Add a "speech bubble" type dialog

### ISSUE THREAD

**Issue by djrain** [coppolaemilio/dialogic#276]
**Is your feature request related to a problem? Please describe.**

Games often include smaller, comic-style dialog bubbles. These tend to have several different characteristics compared to the default dialog popup that Dialogic currently has. Some of these characteristics include:

- tend to be smaller, often scale to fit the text inside
- non-intrusive, don't take control away from player
- one bubble per character (player may or may not have one)
- anchored to the character speaking rather than specific screen position
- might adjust position slightly to stay on screen
- often don't display any character name or portrait
- have a shape connecting the bubble to the character (possibly in a dynamic way)

<img width="476" alt="Screen Shot 2021-05-01 at 12 58 10 PM" src="https://user-images.githubusercontent.com/33777501/116793701-1d0da700-aa7d-11eb-9666-87feb7922765.png">

I'm new to the plugin, but I don't believe there is currently any easy way to accomplish this in Dialogic.

**Describe the solution you'd like**

I propose having two types of dialog popups, one for the bigger more intrusive dialogs, and another type for bubble messages. This new type can offer some or all of the options listed above. I suppose each timeline would probably need to be set to use only one of these two options?

This is just the general idea, I'm sure that others will share their thoughts here.

**Describe alternatives you've considered**

Maybe such options could simply be added to the current popup instead of having two separate types. But given the scope of the differences, I think two types may be necessary.

**Additional context**
none

**Comment by coppolaemilio** [comment]
This issue is highly requested but I don't imagine it coming any time soon. There are too many issues with allowing speech bubbles that won't be easy to solve. If it comes it will surely come in v2 since it will require a rewrite of many of the elements that Dialogic uses to generate the scenes. Thanks for making the issue and hope we can eventually add it :)

**Comment by bitbrain** [comment]
>  There are too many issues with allowing speech bubbles that won't be easy to solve

@coppolaemilio are these issues documented somewhere? I'd be curious to know what the challenges are so I can look into them.

**Comment by AnidemDex** [comment]
_not emilio but_ 
@bitbrain issues are marked with milestones and grouped with labels (most of them). Usually they don't include a workaround or implementation to make 'em possible. Not sure if is that what you were asking for

**Comment by bitbrain** [comment]
@AnidemDex from what I saw Emilio wrote, simply adding speech bubbles seems to be difficult to do as part of 1.x and I try to understand what the challenges are to make speech bubbles happen in 1.x

One thing I suspect is how Dialogic instantiates dialogues and that it is difficult at the moment to make a distinction between "on screen dialogues with user input" and "over-head dialogues displayed in speech bubbles"

**Comment by AnidemDex** [comment]
@bitbrain While trying to implementing it by myself I got these issues:
- Dialogic was made with Visual Novels in mind, so most of the development of the plugin is focused on that (but many people thinks that was made with _any game is suited to use this plugin_ in mind when is not that case).
- Dialogic dialog node uses fixed sizes and positions for **everything**. No idea about why is that that way since they are Control nodes.
- Mixing Control nodes and Node2D types is not something easy (and is something not recommended). As an example, there was a lot of people mixing them both and Emilio ended adding the CanvasLayer by default in the plugin to avoid issues related to that.
- Dialogic uses a very specific instantiation behaviour, and changing it at this point will require to redo the entire node that instances it.

It can be done, I think? But will require to solve those points. I decided to wait until 2.0 is something that is in mind to start making PRs here again, and while that's something, I ended making my own [implementation of dialog node](https://github.com/AnidemDex/Godot-DialogPlugin) from a [fork that I made long ago](https://github.com/coppolaemilio/dialogic/pull/203.)

**Comment by Jowan-Spooner** [comment]
Hey folks, little update on this: The new system in 2.0 allows for very manual creation of themes and there is a handful of example scenes to pick from. One of them is a speech-bubble:
![grafik](https://user-images.githubusercontent.com/42868150/182044751-48c0b46e-0c56-46a6-9b91-9f080e407d50.png)

I think the new system should satisfies all the needs you might have. When 2.0 goes into beta I will try to create a little mock-up scene that actually uses the text bubble on a moving character, but for now I think it's possible feature-wise so I will close this.

**Comment by bitbrain** [comment]
@Jowan-Spooner my body is ready!!!
