### ISSUE TITLE
Drop in performance when opening timelines

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#365]
I runned the editor view scene to check the profiler and found out this:
![image](https://user-images.githubusercontent.com/2206700/122691488-430b2880-d230-11eb-87f4-6176e4d45882.png)

First time opening a timeline:
![image](https://user-images.githubusercontent.com/2206700/122691580-d7758b00-d230-11eb-9a1e-58306db00d9d.png)

More info on calls:
![image](https://user-images.githubusercontent.com/2206700/122691720-b5c8d380-d231-11eb-94e8-92a3b777de82.png)

Still not sure what it could be, but I would love to improve it.

**Comment by Rubonnek** [comment]
If you were using the fonts in the "Example Assets" folder you've provided, and this performance drop only happens the first time opening the timeline and is not seen on subsequent timeline openings, then the root cause could be the use of the dynamic fonts provided.

Godot has to rasterize these fonts in the background before showing them on screen. You could rasterize them before hand with [Hiero](https://github.com/libgdx/libgdx/wiki/Hiero) so Godot does not have to do that at runtime.

**Comment by coppolaemilio** [comment]
The most taxing part is the `create_event` (TimelineEditor.gd:509) which is the one that creates individual events. The creation of individual events should be improved.

**Comment by coppolaemilio** [comment]
Fixed for now, if more updates are needed later I will create a new issue
