### ISSUE TITLE
Add support for resource embedding.

### ISSUE THREAD

**Issue by CardboardCarl** [coppolaemilio/dialogic#386]
**Is your feature request related to a problem? Please describe.**
During my [last game jam](https://ludicorde.itch.io/color-computer-16), I failed to realize Dialogic does not embed it's resources into the executable file (because of this, my game was unplayable for at least a day without me knowing. :/ ) It seems a little inconvenient, especially for game jam games, to have to set up a dedicated folder to play a game. 

**Describe the solution you'd like**
I'd be willing to add the feature myself, though I need to brush up on Dialogic's internal workings. It shouldn't be a hard fix unless there's some reason it's absolutely necessary.

**Describe alternatives you've considered**
I don't know that there is any alternative... :/

**Additional context**
Thanks for all you've done Emilio! I'll try and start helping some where I can.

**Comment by Jowan-Spooner** [comment]
I'm sorry, but I'm unsure what you are talking about. 

For exports you will need to add *json and *cfg in your export settings so that these files will be exported properly. You can find this info on the starting page of this github project. 

Maybe I'm just not understanding the issue, but I never had to add any folder or something

**Comment by CardboardCarl** [comment]
Sorry, I must have missed that. I'll go ahead and close this.

**Comment by coppolaemilio** [comment]
I'll see if there is something we can do better to avoid this from happening in the future. For the moment I modified the readme and placed the export section at the top, and I'll see if I end up transforming some file formats to Godot resources so that you don't have to add any extra flags on the export settings. Thanks for the report and sorry about the game jam :(
