### ISSUE TITLE
Evaluate certain events before starting dialog (e.g. BackgroundImage before fading in)

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#404]
**Is your feature request related to a problem? Please describe.**
Often the first events in my timeline are a background image and a background music. Especially for the background image it is very weird that the dialog fades in for a second and THEN the background appears. 

**Describe the solution you'd like**
For the background image and music I would love if it could notice them and load them in before starting the timeline.

**Describe alternatives you've considered**
Remove the fade in animation

**Comment by RedXGames** [comment]
I would like to share a possible fix too as I find this a little bit unpleasant for user experience.
Instead of removing the fade in animation, The dialogue box should fade in only when detecting the first text event/question event,
Which means if you have a set background event before that it will show first.
I'm also trying to make the backgrounds fade in as well to avoid hard transitions, I will pull a request if I managed to do that.

**Comment by coppolaemilio** [comment]
The only idea I got was to create a virtual event (only created by code) that would add the fade in, but then it doesn't really work as the fade in for all the other nodes. It is a tricky issue to fix, and I'm running into it more and more. I'm not sure if it is because I'm too tired to work on it, or because the poor implementation of the fade in I have now is too intrusive.

**Comment by coppolaemilio** [comment]
Managed to fix a lot of the issues here, but I think that all this will have to be remade for Dialogic 2.0. Feel free to open new issues if you find more specific issues with events fading in at the start of a dialog
