### ISSUE TITLE
Skip/Disable event flag

### ISSUE THREAD

**Issue by zaknafean** [coppolaemilio/dialogic#412]
**Is your feature request related to a problem? Please describe.**
In discussing #410 a case occurred where an event with a missing event_id would be deleted from the timeline JSON during save. If the system could instead flag an event as 'disabled' or 'skip' then the event_data could be elegantly preserved. In addition being able to conditionally skip events would be pretty handy for general debugging. The same system could also be extended to put events into a 'pending delete' state to avoid accidental 'del' key hits many of us are plagued with. 

**Describe the solution you'd like**
An option, probably in the drop down, to set an event to some variant of 'disable'/'skip'/'do not process'. When the parser hits a disabled event, it doesn't do anything to it. It just loads the next event in the timeline. When you re-enable the event, check to make sure the event_id exists, then become enabled, otherwise stay disabled with a quick message saying the event_id can't be found. Disabled events bodies should not be able to be expanded and their headers should be blank. The event_data needs to be preserved, but ignored.

**Describe alternatives you've considered**
I'm open to suggestions, but I think disabling/skipping events is the cleanest way to accomplish this.

**Comment by zaknafean** [comment]
If this seems a reasonable enhancement, I do not mind taking it on myself for what its worth.

**Comment by Jowan-Spooner** [comment]
Hey here are my thoughts on this proposal:

I don't think that an enable/disable flag is the best way to deal with all of these situations, as they are quite different from each other:
- When an event cannot be found we want the data to be stored but be converted back, once the event can be found again. So there should be zero work done by the user
- When deleting we want the user to decide what events should be deleted, but then when the timeline editor is closed, we want all those elements to be deleted automatically
- When you disable events for debugging, then you do NOT want them to be deleted or reenabled by the editor under any circumstances until you enable them back yourself. 

Because all situations/features are nice anyways I propose different solutions:
- For missing events: a dummy event that takes the exact data of the event, but has no editor things except maybe a "This event wasn't found" text. Having the exact same data means it will be shown as the correct one again once it is found.
- For deleting events: I think using the builtin UndoRedo functionality of godot is the best way to go here. I've played around with it before and it's totally doable and cleaner then having those events be "disabled" and then later deleted.
- I think for debugging a skip or disable functionality could be cool and could be implemented with additional data to the event_data of the event.

What do you think?

**Comment by zaknafean** [comment]
Hm ya. My proposal is a bit overloaded, and for the purposes of the custom event unneccesary. 

The skip flag does work pretty well though in my local build, so I'll continue pursuing that for now. Its a helpful exercise to learn the code base better anyway.

**Comment by zaknafean** [comment]
Closing this out as its really not a necessary feature at this point with so many good workarounds.
