### ISSUE TITLE
Setting for unique text color depending on speaker?

### ISSUE THREAD

**Issue by Schwegg** [coppolaemilio/dialogic#457]
Title says all, small addition but would be a really nice addition.

**Comment by coppolaemilio** [comment]
You mean the speaking text for the entire text, right?

**Comment by Schwender-exe** [comment]
yeah, I understand that you can simply add the `[color=]` command in front of each dialogue but having it so the speaker has a specific default text color, I get that it's probably niche but it'd be QOL, or could have something more-so like "default effects on text" which would let you type in or select specific BBCode which would let you have those applied automatically for that speaker, eg.
`CharacterA` and `CharacterA (thoughts)` as two different characters, setting one to italicize and color the text differently automatically or by default for `CharacterA (thoughts)` rather than applying it individually?

**Comment by coppolaemilio** [comment]
yeah, that sounds like something we could add when we improve the characters 👍🏻

**Comment by Jowan-Spooner** [comment]
Hm... I mean this could be the easier solution.
But we could also just have a theme selector on the character editor. By having a theme for your character you could change much more then the color (a different font for example).

**Comment by Jowan-Spooner** [comment]
So in 1.4 (currently WIP) you can set a theme for each character. This means you can also create a theme with a different color for your character. To be honest this is probably still a bit annoying until Theme inheritance #232 is a thing, but I don't think we will add a text color setting to the character editor now. If you disagree, feel free to reopen the issue.
