### ISSUE TITLE
can you port this addon to 3.2.3?

### ISSUE THREAD

**Issue by VictorRandall** [coppolaemilio/dialogic#482]
i making a game that i had to use the 3.2.3 version, but there are no version of dialogic to 3.2.3. Could you please make branch on this project just for 3.2.3?

**Comment by coppolaemilio** [comment]
What is not working in 3.2?

**Comment by VictorRandall** [comment]
well, it doesnt show on the assetlib and when i tried to download to the project files and use in godot, it didnt do anything

**Comment by zaknafean** [comment]
Just for sanity testing I tried the build as it is today in Godot 3.2. It works flawlessly. @VictorRandall make sure you turn it Enable it in your project settings as shown below:

![image](https://user-images.githubusercontent.com/7741797/132988715-936f69ef-070c-492d-82b1-5ae25e01c55d.png)

Otherwise there isn't really an issue here.
