### ISSUE TITLE
Make Filenames easier to find

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#496]
Many people try to do things that are more complex, then what dialogic was orginally intended for. Sometimes they would like to edit the files/values directly. This is made harder by the fact that the filenames are different from what is seen in the editor.

While I definitely want to keep it as clean as possible, I think it would be cool to have the actual filename or (for definitions) the ID visible somewhere in the editors (TimelineEditor, CharacterEditor, ThemeEditor, ValueEditor, GlossaryEditor). Or maybe have an option in the right-click-menu of the items.

**Comment by coppolaemilio** [comment]
Yeah, I think that we should start breaking compatibility more from version to version, because most of the things we are not doing is because we don't want to break previous ones, but we should still be trying to figure out what the best solution for each problem is and implement it in its best form.

We can start drastically changing things after 1.3 and see what needs to happen to make the plugin as flexible and powerful as possible 👍🏻

**Comment by Jowan-Spooner** [comment]
I will close this, because you can now right click the element in the timeline and copy it's real name or id.
