### ISSUE TITLE
Constant I/O while editing the structures

### ISSUE THREAD

**Issue by VinegarLove** [coppolaemilio/dialogic#600]
## Constant IO Writes on disk

While selecting a main category to edit (timelines, characters, definition) Dialogic constantly delete and create files on filesystem leading to sustained IO and FS strain.

**To Reproduce**
1. Click on "Dialogic" topbar
2. Select any of the mentioned category

**Details in the video**
https://youtu.be/yHO1nsEjpWs

**System:**
 - OS: Linux
 - Godot Version: 3.3.4
 - Dialogic Version: 1.3

## Solutions

**Workaround**
This is due to the method **_on_autosave_timeout** called frequently (every 0.5 sec).
I removed the float parameter in the start function call to avoid he override of the scene and set the autosave timer in the scene to 10 sec.

```
$AutoSave.connect("timeout", self, '_on_autosave_timeout')
$AutoSave.start()
```

**Possible fixes**
Raise the autosave time or save the data on memory rather than always on disk.

**Comment by Jowan-Spooner** [comment]
To clarify (just because I was confused by your phrasing), this happens when one of the editors (Timeline, Character, Theme, Definition) is opened, not when you click on the main folder of one of these categories.

Yeah the autosave thing is a known issue. Right now the editors can only save their data, when they are opened. Making the autosave less frequent has the risk of someone changing something and then quickly exiting to a different file before it saves again (meaning the change get's lost).

Obviously we optimally would only want to save when data is changed or even only when the editor is exited (with possible autosaves every minute or similar for crash safety). This is quite a bit of work to get it right tho (especially on the timeline editor), that's why it hasn't been done until now. It would definitly be nice to have a better solution tho, imo.

**Comment by VinegarLove** [comment]
> To clarify (just because I was confused by your phrasing), this happens when one of the editors (Timeline, Character, Theme, Definition) is opened, not when you click on the main folder of one of these categories.

Yes, that's correct.

A solution to avoid changing the code too much could be overriding the resource class to implement a temporary buffer instead of saving/re-opening from FS everytime (i'm not sure if it can be done with a different object, GDScript API or only native code). I'll see what i can do.

**Comment by coppolaemilio** [comment]
Right now we are using Godot's saving signals so I will close this issue
