### ISSUE TITLE
Skipping a question results in unexpected behaviour

### ISSUE THREAD

**Issue by schmertenk** [coppolaemilio/dialogic#633]
## Skipping a question results in unexpectedbehaviour when Autofocus choice buttons is enabled

**Describe the bug**
When skipping a question by hitting the ui_accept event and Autofocus choice buttons is enabled, the name tag disappears the choice buttons won't be shown, and all events in all choices are played

**To Reproduce**
1. Create a question block in a timeline
2. fill the choices with some text events
3. when playing the timeline, skip the question by hitting the the ui_accept button
4. The name tag of the character keeps disapperaring and all text events in the choices blocks are shown one by one

**Expected behavior**
the name tag should be displayed correctly and the choice buttons should be shown

**System:**
 - OS: Windows
 - Godot Version: 3.4
 - Dialogic Version: 1.4 - DEV

**Comment by zaknafean** [comment]
Should be solved with #734. Here is the notes on it.

More or less the initial problem is that with the new state system, the only time input is ignored, is if the DialogNode is in the WAITING or WAITING_INPUT state. Unfortunately the state is TYPING until the choices actually appear at the end of the event. So hitting the 'dialog advance' button will still increment the event index to the next event, which often in choices means that they ALL just fire off one after the other without pause.

Putting the input block when an event has options was a simple enough fix. But then I ran into an edge case where after a fade-in occurred (start of a timeline generally) the state would change to IDLE as soon as the fade in finished, regardless of the base state. That means the state could go from WAITING_INPUT to IDLE just due to essentially a race condition. The easiest fix here was to prevent IDLE from occurring if the current event has options, since answering the options to continue is the expected behavior.

These two changes seem to fix the problem, which I could previously trigger with 100% certainty.

**Comment by Jowan-Spooner** [comment]
Thanks so much for fixing it @zaknafean!
