### ISSUE TITLE
DialogicSharp.cs(52,12): error CS1501: No overload for method 'Start' takes 5 arguments

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [coppolaemilio/dialogic#662]
## The problem

**Describe the bug**
Can't run project

**To Reproduce**
1. Click run
**Expected behavior**
Running

**System (please complete the following information):**
 - OS: Windows
 - Godot Version:3.4
 - Dialogic Version: Latest

DialogicSharp.cs(52,12): error CS1501: No overload for method 'Start' takes 5 arguments

**Comment by DavidBradbury** [comment]
Try opening your `DialogicSharp.cs` file at `/addons/dialogic/Other/DialogicSharp.cs` and replacing it with the contents at https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Other/DialogicSharp.cs

I ran into the same issue and it seems to be fixed in the latest version. If you are using any generic type parameter (`<T>`) you may need to replace:

`String dialogScenePath = ""` on line 16 with

`String dialogScenePath = DEFAULT_DIALOG_RESOURCE`

**Comment by GalaxyGamingBoy** [comment]
^ Worked
