### ISSUE TITLE
Changing "Default Action Key" freezes Godot after closing Project Settings

### ISSUE THREAD

**Issue by BillGr7** [coppolaemilio/dialogic#736]
## The problem

If you change the "Default Action Key" in Dialogic settings, and then open and close Godot's Project Settings, Godot will freeze up with the dark overlay it has while editiing the Project Settings.

**To Reproduce**
1. Go to Dialogic->Settings
2. Under Input Settings, Change Default action key (You can even select the same key already set).
3. On Godot's menu bar, go to Project->Project Settings
4. Close the Project Settings
5. See the issue

**Expected behavior**
Godot doesn't freeze upon closing Project Settings

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 3.4.2
 - Dialogic Version: 1.4

## Solutions

**Workaround**

Closed Godot via closing the console window (since main window wasn't responding).

**Comment by Jowan-Spooner** [comment]
Cannot recreate.

**Comment by BillGr7** [comment]
I did a little bit more testing, and I think it's tied to having the Left Mouse Button setup as the ui_accept button.  The issue went away when I removed it, and came back when I added it again.

**Comment by Jowan-Spooner** [comment]
Alright I think the issue is cause by this line 
![grafik](https://user-images.githubusercontent.com/42868150/154851025-5c3d3cb2-d309-4d06-8896-454c57d70179.png)
I do not know why it is in there, and I don't think it's supposed to be called in the editor. I will investigate if there was a reason it was added, because so far removing it has not seemed to change anything.

**Comment by Jowan-Spooner** [comment]
This has turned out to be much more annoying then I thought it would be. Although I will still try to fix it, I would mainly suggest not to use the build in ui_* actions for anything and also not to modify them, because it will mess with the control nodes in your game (and currently also in the editor if you change the action in the dialogic settings).
If possible, I would suggest zo create a new dialog default input action when dialogic is created and use that one.

**Comment by Jowan-Spooner** [comment]
I do believe I have found a way to get the list differently. I will try it out this evening if I can. I think I will also create an issue though, because this should not be that annoying to do.
