### ISSUE TITLE
Create mechanism for branching dialogue paths

### ISSUE THREAD

**Issue by willnationsdev** [coppolaemilio/dialogic#8]
Derived from a YouTube comment I made on your first devlog.

- Allow a dialogue sequence to `divert` to another dialogue sequence.
- Allow a `diverted-to` dialogue to pull data from the `diverted-from` dialogue, such as...
    - scene settings
    - current speakers
    - conversational variables
    - etc.
- Store data in a resource that tracks the dependencies of each dialogue (both to and from references). Use this to power UI elements in the dialogue editor that displays a list of incoming and outgoing dialogue sequences related to the currently opened one.
- Allow users to generate a graph view of how dialogue sequences are related to one another. Generated. Clicking on a dialogue in the graph would open it.

This would necessarily require occupying screen space on the left-hand side that is currently being used for events, folding, and script attachment. See #7 for more details on modifying the UI to accommodate things (including more complex navigation).

**Comment by coppolaemilio** [comment]
You can now branch dialogs using the change timeline events and questions/choices. I'll probably have to add a "chapter" feature in the future because there can be many timelines for one particular part of a story and it would end up being overwhelming as soon as the game gets a bit bigger. Closing this for now 👍🏻
