### ISSUE TITLE
Dialogic Code Cleanup/Simplification

### ISSUE THREAD

**Issue by Jowan-Spooner** [coppolaemilio/dialogic#838]
This issue is supposed to be a place to collect things that are currently working well, but have some terrible code behind the scenes.
It's not about changing the behaviour of things if possible. 
I just wanted a place to note these things down, whenever I find them, and not create a separate issue for each one.

- [ ] DialogicUtil.get_character_list() creates an unnecessary layer of complexity by creating a new dict with the same info AND the original dict for each character. Unfortunately some other parts of dialogic are build around this layer, so the effects of removing/changing this are hard to predict. 
- [ ] DialogNode.update_custom_events() is deprecated, but still present.
- [ ] DialogicDefinitionsUtil.set_definition_variable() and .set_glossary_variable() require you to provide everything about the definition as separate arguments, meaning any change to the content of a definition also requires the change of these functions even though all they do is put that EXACT values into a dictionary. It would be much easier to add a single content or data argument that would be a dictionary.

More will come over time I'm sure. Feel free to suggest things I should add to this.

**Comment by thebardsrc** [comment]
one thing I would add is the over complicated nature of the implementation of the folder structure since they were added after the fact, and to a lesser extent an issue with the 

currently this happens on every time in the following order whenever you try to do a lookup with the folder path:

1. the entire folder structure JSON is loaded into a new Dictionary
2. the dictionary is iterated through once to find a matching path to find the matching ID... multiple unnecessary steps happen at this phase, at each level of the folder tree as it searches, with for variables another Dictionary of all the variables is pulled from the Engine meta definition store and then fully looped through multiple times at each tree level to find a matching ID, and for timelines it has to load and check every single timeline file _at each tree level_ to see if it's a matching one
3. once the ID is finally from the search function, theyre passed to the actual function that's using them... which then has to do _one more_ pull of the Engine meta into another copy Dictionary, or another check of the timeline files to get the matching one to pass on and process

it's massively over complicated, with way too many loops and extra data thats created and discarded. and even for the cases that don't use the full path, its only partially simplified by removing step 2, the additional extra steps in 3 are still happening too. 

ideally this could all be solved by a few one-time extra steps at load time. first, when the definitions are first loaded at runtime and stored in the Engine meta, it currently adds a dictionary with values of ID, Name, Type, and Value. an additional value should be added of Path so that is stored as well and always available. second, an additonal dictionary should be generated at runtime and stored in the Engine meta for the Timelines so it doesn't have to keep reading those from the files, also with ID, Name, and Path. 

with those changes, it would be possible to dramatically speed up both variable and timeline lookup, since you only need just the ID or the Path+Name to iterate through the dictionaries once. It brings the search speed down to O(n), from something so complicated I don't even know _how_ to classify it right now, and cuts out a lot of unnecessary memory allocation and garbage collection as well

**Comment by Jowan-Spooner** [comment]
This issue is outdated (at least for 2.0) as the near-complete rewrite means the problems mentioned above aren't in 2.0.
