### ISSUE TITLE
Plays it's self

### ISSUE THREAD

**Issue by Scsundyy** [coppolaemilio/dialogic#854]
Just wanted to try this out, but the dialog and choices play them self.

Don't know what is wrong, I just tried to follow the tutorial that was posted.

Pliz help

**Comment by qskousen** [comment]
I think more information is needed in order to help you.

If you are adding the dialog to the scene via the UI (dragging and dropping the dialog scene into your scene, for example), it should be playing automatically as you described. If you only want it to play on a certain trigger, like the user presses a key to interact with an NPC, you will need to add it via script.

**Comment by Jowan-Spooner** [comment]
If it isn't fixed by what qskousen suggested (adding it via script), then please give more information.

**Comment by zaknafean** [comment]
This is not reproducable and doesn't appear to be an actual bug and more an implementation problem. Closing the issue as we also haven't heard back from the user in nearly 2 months.
