### ISSUE TITLE
Character name color 

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#893]
From Lucas Molina on Twitter:

Dialogic 1.4.1.

After a character that has a custom theme speaks, the color of the name of the next character that speaks changes to white for one line of dialogue, then changes back to the actual color it is supposed to be.

I'm sending you a gif of the bug. The name 'Waitress' should never appear as white, yet it does. The bug is reproducible 100% of the time for me.

https://user-images.githubusercontent.com/2206700/168375373-c298f30f-4e97-40bb-9631-16bca133c93c.mp4

**Comment by zaknafean** [comment]
Can confirm this one, hits me all the time.

**Comment by Yotopihi-Dev** [comment]
Not sure if this may be the issue, but in the theme editor theres an option for the character's color to be its own original version, so if the character has its own specific theme and is switching around in the timeline it may be overlapping, just an idea though.

**Comment by Yotopihi-Dev** [comment]
Also, there's another thing. I saw somebodies character text change colors because the dialog called the name
![Screenshot_2022-05-15_150305](https://user-images.githubusercontent.com/101610280/168541356-95f236eb-c7fb-4697-8929-92b5c7385df4.png)
![Screenshot_2022-05-15_150257](https://user-images.githubusercontent.com/101610280/168541368-2dd6660a-a7f0-4cc1-bd5d-2a830819ad53.png)

**Comment by zaknafean** [comment]
This is fixed in main as of #902

**Comment by AD1337** [comment]
Thanks for fixing this @zaknafean!
