### ISSUE TITLE
Files being automatically overritten without concent 

### ISSUE THREAD

**Issue by Aki78** [coppolaemilio/dialogic#935]
**Describe the bug**
I am not sure if it is a bug or a feature but, when I update .json files externally with another text-editor while godot is running, all progress were lost because it keeps getting overwritten.

**To Reproduce**
1. Change .json file content externally
2. Check content at a later time or leave editor and come back

**Expected behavior**
File was overwritten and update is lost.

**System (please complete the following information):**
 - OS: [Linux]
 - Godot Version: [e.g. 3.4]
 - Dialogic Version: [e.g. 1.4]

## Solutions

**Workaround**
Keep godot closed, however, it is hard to work without the UI.

What you tried to get the feature working

**Possible fixes**
Possibly auto-update dialogic timeline when external changes happened.

**Comment by coppolaemilio** [comment]
With version 1 of Dialogic you are not supposed to edit those file manually. 
In the new 2.x branch this kind of external edits will be included since we are also moving away from json to a plain text format similar to frameworks like renpy. 

I will unfortunately close this issue now because we are not going to be changing things like that in the current 1.4 version, but feel free to reopen if this still happens after we release the version 2.0

Thanks!
