### ISSUE TITLE
Variables not working on exported projects.

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#95]
It seems that when you save files to a location in `res://` instead of  `user://` they cannot be changed in exported games. I think we should make a copy of the definitions.cfg in the `user://` path to allow for persistent data. 

I'm tagging @arnaudvergnet since you were working on this part of dialogic already

**Comment by arnaudvergnet** [comment]
Would this allow for persistent saves across runs? I'm kinda new to Godot so I'm figuring out stuff as I go.

If this is the case, the `.cfg` in `res://` would be the default/reset values, and the `.cfg` in `user://` would be the current variables. We would then have to make a copy on the very first run, then only use that copy to read/write definitions. We would also need to create a method for the user to access default values and reset current definitions, in the case of a new game for example.

Is that what you were thinking about?

**Comment by coppolaemilio** [comment]
Yes, exactly that! Right now I'm using the `DialogicSingleton` to store a `runtime_id` and accessing a copy of the variable in the same `definitions.cfg` file, but it should be reading/writing off a new file so it works in exported games.

**Comment by arnaudvergnet** [comment]
Putting relevant doc link here: https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html

If I understand correctly, moving `definitions.cfg` in `user://` will store it inside a specific folder, not next to the executable, and the `/dialogic` folder will not be needed anymore as it should be packed inside the `.pck` file.

Seems like a very good approach, make the game more portable.

This issue seems linked to #76. We could rework definitions to let the user specify if changes should be persistent or not.

**Comment by arnaudvergnet** [comment]
@coppolaemilio I am working on a DialogicResources class to handle external files, like loading cfg and json. This will be easier to work on this issue.
